remove stages for testing

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -17,12 +17,29 @@ image: $SKA_K8S_TOOLS_BUILD_DEPLOY
 
 
 stages:
+  - lint
   - build
+  - test
   - deploy
   - integration
   - staging
+  - join-reports
+  - pages
   - publish
   - scan
+
+#Join linting reports (This stage is temporary!)
+join_linting_reports:
+  stage: join-reports
+  tags:
+    - k8srunner
+  script:
+    - echo "This step is needed as the artifacts can't be passed in the same stage"
+    - make join-lint-reports
+  artifacts:
+    paths:
+      - build/
+    when: always
 
 # Standardised included jobs
 variables:
@@ -36,6 +53,10 @@ include:
   - project: 'ska-telescope/templates-repository'
     ref: "st-1889-vault-pki-image-signing"
     file: 'gitlab-ci/includes/oci-image.gitlab-ci.yml'
+
+# Python packages build,lint, test and publish
+  - project: 'ska-telescope/templates-repository'
+    file: 'gitlab-ci/includes/python.gitlab-ci.yml'
 
 # Jupyter notebook linting and testing
   - project: 'ska-telescope/templates-repository'
@@ -64,3 +85,65 @@ include:
 # deploy steps
   - project: 'ska-telescope/templates-repository'
     file: 'gitlab-ci/includes/deploy.gitlab-ci.yml'
+
+python-test:
+  before_script:
+    - '[ -f .make/python.mk ] || (echo "File python.mk not included in Makefile; exit 1")'
+    - 'make help | grep python-test'
+    - poetry config virtualenvs.in-project true
+    - echo "python-build Setting.. poetry config virtualenvs.create $POETRY_CONFIG_VIRTUALENVS_CREATE"
+    - poetry config virtualenvs.create $POETRY_CONFIG_VIRTUALENVS_CREATE
+    - |
+      if [[ ! -z "$PYTANGO_VERSION"  ]]; then \
+        echo "Received pytango version: $PYTANGO_VERSION" ; \
+        poetry add pytango==$PYTANGO_VERSION
+      fi
+      if [[ -f pyproject.toml ]]; then
+        echo "python-test: Installing with poetry";
+        time poetry install;
+      else
+        if  [[ -f requirements.txt ]]; then
+          echo "python-test: Installing with pip";
+          time pip3 install -r requirements.txt;
+        fi;
+      fi;
+
+# if the pipeline is called from an upstream project (ska-tango-images) 
+# we don't lint, there's no need
+python-lint:
+  rules:
+    - if: '$PYTANGO_VERSION == ""'
+    - if: '$PYTANGO_VERSION == null'
+
+
+k8s-test-no-operator:
+  extends: k8s-test
+  variables:
+    KUBE_NAMESPACE: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-no-op'
+    SKA_TANGO_OPERATOR: 'false'
+  artifacts:
+    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
+    paths:
+      - "build/"
+    reports:
+      junit: build/report.xml
+    when: always
+  environment:
+    name: test/$CI_COMMIT_REF_SLUG-no-op
+    on_stop: stop-k8s-test-no-operator
+    auto_stop_in: 1 minute
+  rules:
+    - exists:
+        - tests/**/*
+
+stop-k8s-test-no-operator:
+  extends: stop-k8s-test
+  when: manual
+  variables:
+    KUBE_NAMESPACE: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-no-op'
+  environment:
+    name: test/$CI_COMMIT_REF_SLUG-no-op
+    action: stop
+
+notebook-test:
+  when: manual
